### ISSUE TITLE
Utiliza un almacenamiento más seguro para tus contraseñas, todo el mundo las puede ver

### ISSUE THREAD

**Issue by YeyoM** [Donatelatrump/Telegram-bot-Web-scrapping-aula-virtual-UAA#1]
Utiliza un almacenamiento más seguro para tus contraseñas en el archivo Program.cs, https://learn.microsoft.com/es-es/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows

**Comment by Donatelatrump** [comment]
Muchas gracias buen samaritano
